### ISSUE TITLE
Paths in build

### ISSUE THREAD

**Issue by creativar** [wimdeblauwe/vite-spring-boot#1]
I am sure I am probably doing something incorrect in my config to cause this problem. Am I doing something incorrect?

I am integrating into an existing project that used to use your older thymeleaf-live-reload plugin with gulp (which I built after reading the awesome taming thymeleaf book :-) )

Local development with mvn spring-boot:run and yarn dev works perfectly. 

I have yarn build running when I run spring-boot:build-image. It generates 

`{
  "static/css/app.css": {
    "file": "css/main-hp7geRny.css",
    "src": "static/css/app.css",
    "isEntry": true
  }
}`

Which from the follwing in thymleaf 

    <vite:vite>
        <vite:entry value="/css/app.css"></vite:entry>
    </vite:vite>
    
 creates  <link rel="stylesheet" href="css/main-hp7geRny.css">
    
which on root domain like example.com/ works but on a path like example.com/test it does not. 

My current vite config: 

```
import { defineConfig } from 'vite';
import path from 'path';
import springBoot from '@wim.deblauwe/vite-plugin-spring-boot';
import autoprefixer from 'autoprefixer';
import tailwindcss from 'tailwindcss';

export default defineConfig({
  plugins: [
    springBoot({
        fullCopyFilePaths: {
            include: ['**/*.html', '**/*.svg', '**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.ico', '**/*.xml',  '**/*.manifest']
        }
    }),
  ],
  root: path.join(__dirname, './src/main/resources'),
  base: '/',  // Ensure assets are served from root
  build: {
    manifest: true,  // Ensure the manifest file is created
    rollupOptions: {
      input: {
        main: '/static/css/app.css',  // Entry point for CSS
      }
    },
    outDir: path.join(__dirname, './target/classes/static'),  // Output to Spring Boot's static folder
    copyPublicDir: false,  // Skip copying the public directory
    emptyOutDir: false,  // Clear the output directory before building
    assetsDir: 'css'
  },
  css: {
    postcss: {
      plugins: [
        tailwindcss,
        autoprefixer,
      ]
    }
  },
  server: {
    proxy: {
      // Proxy all backend requests to Spring Boot except for static assets
      '^/(?!static|assets|.*\\.(js|css|png|svg|jpg|jpeg|gif|ico|woff|woff2)$)': {
        target: 'http://localhost:8080',  // Proxy to Spring Boot backend
        changeOrigin: true,
        secure: false,
      },
    },
    watch: {
      ignored: ['**/target/**'],  // Ignore target directory
    },
  },
});

```

At the moment I have a script to manually modify the manifest after it has been generated to fix the path, which is less than ideal, but works for now.

This is a great set of libraries, but I do wonder if a bit more documentation or detailed examples wouldn't go astray if you have the time.

**Comment by wimdeblauwe** [comment]
On a side note, you have some interesting options configured here, which I might also add by default when I generate a project with ttcli:

1) The `postcss.config.js` is probably no longer needed if you have that `css` section in there? Always nice to have less config files cluttering up the root of the project.
2) The `server.proxy` config: I just tried that and it allows to view the application on http://localhost:5173 as well as http://localhost:8080 which I normally use, so that is nice.

What does `assetsDir: 'css'` do exactly?

**Comment by creativar** [comment]
assetsDir: 'css' allows to choose directory name for generated static assets https://vite.dev/config/build-options#build-assetsdir

**Comment by creativar** [comment]
I did resolve this it was a mistake in the thymeleaf templates 🤦‍♂️
